[versions]
    compile-sdk = "34"
    min-sdk = "26"
    kotlin = "1.8.20"
    gradle-plugin = "7.4.0"
    core-ktx = "1.12.0"
    activity-compose = "1.8.1"
    appcompat = "1.6.1"
    material = "1.10.0"
    constraint-layout = "2.1.4"
    lifecycle = "2.2.0"
    lifecycle-ktx = "2.6.2"
    fragment = "1.6.2"
    compose-bom = "2023.10.01"
    kotlin-compiler-extension = "1.4.6"
    kotlinx-serialization-version = "1.5.0"
    legacy-support-v4 = "1.0.0"
    androidx-preference = "1.2.1"
    androidx-annotation = "1.7.0"
    coroutines-version = "1.7.3"
    zxing = "3.4.0"
    volley = "1.2.1"
    biometrics = "1.2.0-alpha05"
    cbor = "0.9"
    exif = "1.3.6"
    bouncy-castle = "1.70"
    sonar-gradle-plugin = "3.4.0.2513"
    jacoco = "0.47.0"
    navigation = "2.7.5"
    work-version = "2.8.1"
    navigation_plugin = "2.5.3"
    code_scanner = "2.1.0"
    junit-android-test = "1.1.5"
    espresso-core = "3.5.1"
    junit-jupiter = "5.10.0"
    truth = "1.1.5"
    navigation-compose = "2.7.5"
    camera-version = "1.3.1"
    scuba-version = "0.0.25"
    jmrtd-version = "0.7.30"
    mlkit-version = "16.0.0"
    kotlinx-coroutines = "1.8.0-RC2"
    junit = "4.13.2"

[libraries]
    androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "core-ktx" }
    androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activity-compose" }
    androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
    androidx-material = { module = "com.google.android.material:material", version.ref = "material" }
    androidx-contraint-layout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraint-layout" }
    androidx-fragment-ktx = { module = "androidx.fragment:fragment-ktx", version.ref = "fragment" }
    androidx-legacy-v4 = { module = "androidx.legacy:legacy-support-v4", version.ref = "legacy-support-v4" }
    androidx-preference-ktx = { module = "androidx.preference:preference-ktx", version.ref = "androidx-preference" }
    androidx-work = { module = "androidx.work:work-runtime-ktx", version.ref = "work-version"}

    androidx-lifecycle-extensions = { module = "androidx.lifecycle:lifecycle-extensions", version.ref = "lifecycle" }
    androidx-lifecycle-livedata = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "lifecycle-ktx" }
    androidx-lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle-ktx" }

    androidx-navigation-ktx = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "navigation" }
    androidx-navigation-ui-ktx = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "navigation" }

    kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref="kotlinx-coroutines" }
    kotlinx-coroutines-guava = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-guava", version.ref="kotlinx-coroutines" }

    compose-bom = { module = "androidx.compose:compose-bom", version.ref="compose-bom" }
    compose-ui = { module = "androidx.compose.ui:ui" }
    compose-foundation = { module = "androidx.compose.foundation:foundation" }
    compose-material = { module = "androidx.compose.material3:material3" }
    compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling-preview" }
    compose-preview = { module = "androidx.compose.material:material-icons-extended" }
    compose-icons = { module = "androidx.compose.ui:ui-tooling" }
    compose-runtime-livedata = { module = "androidx.compose.runtime:runtime-livedata" }

    volley = { module = "com.android.volley:volley", version.ref = "volley" }

    kotlinx-serialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization-version" }

    androidx-biometrics = { module = "androidx.biometric:biometric", version.ref = "biometrics" }
    androidx-zxing-core = { module = "com.google.zxing:core", version.ref = "zxing" }
    androidx-annotation = { module = "androidx.annotation:annotation", version.ref = "androidx-annotation"}

    cbor = { module = "co.nstant.in:cbor", version.ref = "cbor" }

    exifinterface = { module = "androidx.exifinterface:exifinterface", version.ref = "exif" }

    bouncy-castle-bcprov = { module = "org.bouncycastle:bcprov-jdk15on", version.ref = "bouncy-castle" }
    bouncy-castle-bcpkix = { module = "org.bouncycastle:bcpkix-jdk15on", version.ref = "bouncy-castle" }

    code-scanner = { module = "com.budiyev.android:code-scanner", version.ref = "code-scanner" }

    androidx-test-ext-junit = { module = "androidx.test.ext:junit", version.ref = "junit-android-test" }
    androidx-test-espresso = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso-core" }

    jupiter = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit-jupiter" }
    junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit-jupiter" }
    kotlinx-coroutine-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines-version" }
    truth = { module = "com.google.truth:truth", version.ref = "truth" }
    androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigation-compose" }

    androidx-camera-lifecycle = { group = "androidx.camera", name = "camera-lifecycle", version.ref = "camera-version" }
    androidx-camera-view = { group = "androidx.camera", name = "camera-view", version.ref = "camera-version" }
    androidx-camera-camera2 = { group = "androidx.camera", name = "camera-camera2", version.ref = "camera-version" }
    net-sf-scuba-scuba-sc-android = { group = "net.sf.scuba", name = "scuba-sc-android", version.ref="scuba-version" }
    org-jmrtd-jmrtd = { group = "org.jmrtd", name ="jmrtd", version.ref="jmrtd-version" }
    com-google-mlkit-text-recognition = { group = "com.google.mlkit", name = "text-recognition", version.ref="mlkit-version" }
    junit = { group = "junit", name = "junit", version.ref = "junit" }

[bundles]
    androidx-core = ["androidx-core-ktx", "androidx-appcompat", "androidx-material", "androidx-contraint-layout", "androidx-fragment-ktx", "androidx-legacy-v4", "androidx-preference-ktx", "androidx-work"]
    androidx-lifecycle = ["androidx-lifecycle-extensions", "androidx-lifecycle-livedata", "androidx-lifecycle-viewmodel"]
    androidx-navigation = ["androidx-navigation-ktx", "androidx-navigation-ui-ktx"]
    androidx-activity-compose = ["androidx-activity-compose"]
    compose = ["compose-ui", "compose-foundation", "compose-material", "compose-ui-tooling", "compose-preview", "compose-icons"]
    androidx-crypto = ["androidx-biometrics", "androidx-zxing-core"]
    bouncy-castle = ["bouncy-castle-bcprov", "bouncy-castle-bcpkix"]
    ui-testing = ["androidx-test-ext-junit", "androidx-test-espresso", "truth"]
    unit-testing = ["jupiter", "kotlinx-coroutine-test", "truth"]

[plugins]
    android-application = { id = "com.android.application", version.ref = "gradle-plugin" }
    android-library = { id = "com.android.library", version.ref = "gradle-plugin" }
    dokka = { id = "org.jetbrains.dokka", version.ref = "kotlin"}
    kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
    kotlinx-serialization-plugin = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
    sonarqube = { id = "org.sonarqube", version.ref = "sonar-gradle-plugin" }
    jacoco = { id = "org.kordamp.gradle.jacoco", version.ref = "jacoco" }
    navigation-safe-args = { id = "androidx.navigation.safeargs.kotlin", version.ref = "navigation_plugin" }
    kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
    parcelable = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }
