[package]
name = "circuits"
type = "bin"
authors = [""]
compiler_version = ">=0.22.0"

[dependencies]
sha2 = { tag = "v0.0.3", git = "https://github.com/michaelelliot/noir-sha2", directory = "crates/noir-sha2" }